### ISSUE TITLE
Tooltip should be able to be padded from its master

### ISSUE THREAD

**Issue by shamilovtim** [victorevox/simple_tooltp#1]
Neither the tooltip nor its master can be positioned independently.

Ideally the two should be able to be positioned separately with the ability to control how far away the tooltip is padded from its master.

**Comment by shamilovtim** [comment]
Just found the problem actually. Going to revisit this ticket momentarily.

**Comment by victorevox** [comment]
Hi @shamilovtim , thanks for checking, I'll close this issue in favor of others that are related sounds good?

https://github.com/victorevox/simple_tooltp/issues/4
