### ISSUE TITLE
minimumOutsidePadding is removing size from the tooltip rather than pushing it out

### ISSUE THREAD

**Issue by shamilovtim** [victorevox/simple_tooltp#2]
When a tooltip is near an edge and has minimumoutsidepadding it becomes smaller on one side rather than simply pushing the tooltip over. This gives an asymmetrical lopsided effect to the inner padding of the tooltip itself and is a visual bug. 

Instead: this setting should push the tooltip over, not remove width from the tooltip.

<img width="104" alt="Screen Shot 2020-03-23 at 5 25 41 PM" src="https://user-images.githubusercontent.com/3495974/77364819-64c6e880-6d2b-11ea-8c4e-385c42376e93.png">

**Comment by victorevox** [comment]
Hi @shamilovtim , thanks for checking, I'll close this issue in favor of others that are related sounds good?

https://github.com/victorevox/simple_tooltp/issues/4
