### ISSUE TITLE
minWidth doesn't work and throws errors

### ISSUE THREAD

**Issue by shamilovtim** [victorevox/simple_tooltp#3]
Using `minWidth: 200` receive error: 

The following assertion was thrown during performLayout():
BoxConstraints has non-normalized width constraints.

The offending constraints were: BoxConstraints(200.0<=w<=76.0, 0.0<=h<=667.0; NOT NORMALIZED)
The relevant error-causing widget was
    CupertinoTabView 
lib/main.dart:97
When the exception was thrown, this was the stack
#0      BoxConstraints.debugAssertIsValid.<anonymous closure>.throwError 
package:flutter/…/rendering/box.dart:510
#1      BoxConstraints.debugAssertIsValid.<anonymous closure> 
package:flutter/…/rendering/box.dart:545
#2      BoxConstraints.debugAssertIsValid 
package:flutter/…/rendering/box.dart:558
#3      RenderCustomSingleChildLayoutBox.performLayout 
package:flutter/…/rendering/shifted_box.dart:1122
#4      RenderObject.layout 
package:flutter/…/rendering/object.dart:1724
...
The following RenderObject was being processed when the exception was fired: RenderCustomSingleChildLayoutBox#b9476 relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
RenderObject: RenderCustomSingleChildLayoutBox#b9476 relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
    parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
    constraints: BoxConstraints(0.0<=w<=375.0, 0.0<=h<=667.0)
    size: Size(375.0, 667.0)
    child: RenderStack#5d85f NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
        parentData: offset=Offset(0.0, 0.0)
        constraints: MISSING
        size: MISSING
        alignment: AlignmentDirectional.topStart
        textDirection: ltr
        fit: passthrough
        overflow: clip

**Comment by victorevox** [comment]
Hi @shamilovtim , thanks for the feedback, this issue should be gone
