### ISSUE TITLE
Default behavior should be appearing and disappearing on tap

### ISSUE THREAD

**Issue by shamilovtim** [victorevox/simple_tooltp#5]
![Screen Recording 2020-03-23 at 6 19 14 PM](https://user-images.githubusercontent.com/3495974/77368591-ef5f1600-6d32-11ea-932b-bd4c1f0b4c8d.gif)

The touch callback is useful for customization but the plugin shouldn't require to configure your own gesture handling. By default the behavior should be like the gif.

**Comment by rgb1380** [comment]
It works perfectly the way it is. A main use case is to provide hints when new functionality is introduced and without user action one wants to show the tooltip. It is easy enough to make it appear and disappear on tap for other use cases.

**Comment by victorevox** [comment]
Hi I added this feature on the latest release, look at the `hideOnTooltipTap`  property
