### ISSUE TITLE
toolTipTap only covers the contained child

### ISSUE THREAD

**Issue by rgb1380** [victorevox/simple_tooltp#8]
tooTipTap function is only fired when the contained child element of tooltip is pressed. Change the coverage area to the entire tooltip (the area covered by balloonPadding).

**Comment by victorevox** [comment]
Hi @rgb1380 , sorry for the late response, does this issue stills occurs in the latest version? Thanks!

**Comment by rgb1380** [comment]
No issues in the latest version. Thanks.
